language: node_js
node_js:
  - "0.10"
before_install:
- "./ci/start_neo4j_server.sh"
services:
  - redis-server
jdk:
- openjdk7
notifications:
  hipchat:
    rooms:
      - Bdh0l/7Oworx1yU268O6r9c3YwRPD0TVt/hvRpetN14BjBqhCCS4zTQrihDjxrvlV+CQ0O5YOgDTqEgxDrxz5j1LXy0VEITLlBEPFifsUgXpWDpbHYQL2UWnuj6wtTlerleTgGmUBg2tsAV5R/z5JJs5WMk4tdjAIyTZhrttLXc=@Activity Streams!
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
